apiVersion: apps/v1
kind: Deployment
metadata:
  name: webserver
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    spec:
      containers:
      - env:
        - name: API_ROOT
          value: {{ .Values.apiRoot | quote }}
        image: {{ .Values.openmsiImage | quote }}
        imagePullPolicy: IfNotPresent
        name: webserver
        resources: {}
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            add:
            - NET_BIND_SERVICE
            drop:
            - ALL
          privileged: false
          readOnlyRootFilesystem: false
          runAsNonRoot: false
          runAsUser: {{ .Values.uid }}
        stdin: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        tty: true
        volumeMounts:
        - mountPath: /data/db
          name: vol1
        - mountPath: /data/openmsi/omsi_data
          name: vol2
          readOnly: true
        - mountPath: /project/projectdirs/openmsi
          name: vol3
          readOnly: true
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext:
        fsGroup: {{ .Values.gid }}
      terminationGracePeriodSeconds: 30
      volumes:
      - name: vol1
        persistentVolumeClaim:
          claimName: sqlite
      - hostPath:
          path: {{ .Values.omsiDataPath | quote }}
          type: Directory
        name: vol2
      - hostPath:
          path: {{ .Values.openmsiPath | quote }}
          type: Directory
        name: vol3
status: {}
